# The entire pipeline was shamelessy borrowed from https://github.com/NabuCasa/silabs-firmware-builder
# Kudos to NabuCasa and Stefan

name: Application and bootload builder

on:
  workflow_call:
    inputs:
      sdk_version:
        required: true
        type: string

      device:
        description: Device Part Name
        required: true
        type: string

      board:
        description: Board Id
        required: true
        type: string
      
      build_btl:
        description: "Build Bootloader"
        required: false
        default: false
        type: boolean

      image_name:
        required: false
        type: string
        default: "ghcr.io/${{ github.repository_owner }}/silabs-project-builder:${{ inputs.sdk_version }}"
  
      app_ota_string:
        required: false
        type: string
        default: Raz-1 Torch / TBS2

      btl_version:
        required: true
        type: string


jobs:
  app-firmware-build:
    if: ${{ !inputs.build_btl }}
    name: Zigbee Torch App (no bootloader)
    strategy:
      fail-fast: false
      matrix:
        include:
          - name_suffix: debug

          - name_suffix: end-device
            without: >-
              debug_swo
            configuration: >-
              SL_ZIGBEE_DEBUG_STACK_GROUP_ENABLED_DEFAULT:0,
              SL_ZIGBEE_DEBUG_CORE_GROUP_ENABLED_DEFAULT:0,
              SL_ZIGBEE_DEBUG_APP_GROUP_ENABLED_DEFAULT:1,
              SL_ZIGBEE_DEBUG_ZCL_GROUP_ENABLED_DEFAULT:0

    uses: zha-ng/workflows-silabs/.github/workflows/slc-project-builder.yaml@v1
    with:
      image_name: ${{ inputs.image_name }}
      src_project: TBS2Torch
      project_name: TBS2Torch-${{ matrix.name_suffix }}
      device: ${{ inputs.device }}
      components: ${{ inputs.board }}
      remove_components: ${{ matrix.without }}
      configuration:  |
        ${{ matrix.configuration }},
        SL_IOSTREAM_USART_VCOM_RX_BUFFER_SIZE:32
      extra_c_defs: ""
      sdk_version: ${{ inputs.sdk_version }}
      sdkpatchpath: "patches/GeckoSDK"
      metadata_extra: "{}"
      ota_string: ${{ inputs.app_ota_string }}
      sdk_extensions: |
        "https://github.com/Adminiuga/Raz1_custom_components_extension"
  

  app-btl-firmware-build:
    if: ${{ inputs.build_btl }}
    needs: [ bootloader-build ]
    name: Zigbee Torch App (with bootloader)
    strategy:
      fail-fast: false
      matrix:
        include:
          - name_suffix: debug

          - name_suffix: end-device
            without: >-
              debug_swo
            configuration: >-
              SL_ZIGBEE_DEBUG_STACK_GROUP_ENABLED_DEFAULT:0,
              SL_ZIGBEE_DEBUG_CORE_GROUP_ENABLED_DEFAULT:0,
              SL_ZIGBEE_DEBUG_APP_GROUP_ENABLED_DEFAULT:1,
              SL_ZIGBEE_DEBUG_ZCL_GROUP_ENABLED_DEFAULT:0

    uses: zha-ng/workflows-silabs/.github/workflows/slc-project-builder.yaml@v1
    with:
      image_name: ${{ inputs.image_name }}
      src_project: TBS2Torch
      project_name: TBS2Torch-${{ matrix.name_suffix }}
      device: ${{ inputs.device }}
      components: ${{ inputs.board }}
      remove_components: ${{ matrix.without }}
      configuration:  |
        ${{ matrix.configuration }},
        SL_IOSTREAM_USART_VCOM_RX_BUFFER_SIZE:32
      extra_c_defs: ""
      sdk_version: ${{ inputs.sdk_version }}
      sdkpatchpath: "patches/GeckoSDK"
      metadata_extra: "{}"
      ota_string: ${{ inputs.app_ota_string }}
      sdk_extensions: |
        "https://github.com/Adminiuga/Raz1_custom_components_extension"
      with_bootloader: ${{ needs.bootloader-build.outputs.project_name }}


  bootloader-build:
    if: inputs.build_btl
    name: Application bootloader
    uses: zha-ng/workflows-silabs/.github/workflows/slc-project-builder.yaml@v1
    with:
      image_name: ${{ inputs.image_name }}
      src_project: >-
        ${{ vars.btl_project_name != ''
            && vars.btl_project_name
            || 'bootloader-storage-spiflash-single'
        }}
      src_project_path: >-
        ${{
          vars.btl_template_path != ''
          && vars.btl_template_path
          || ( startsWith(inputs.device, 'EFR32MG1')
               && '/gecko_sdk/platform/bootloader/sample-apps/Series-1'
               || '/gecko_sdk/platform/bootloader/sample-apps/Series-2'
              )
        }}

      project_name: "TBS2Torch_btl"
      device: ${{ inputs.device }}
      components: >
        ${{ inputs.board != '' && format('{0},', inputs.board) || '' }}
        bootloader_compression_lzma
      configuration:  |
        BOOTLOADER_WRITE_DISABLE:1,
        BOOTLOADER_VERSION_MAIN_CUSTOMER:${{ inputs.btl_version }},
        BTL_STORAGE_SPIFLASH_MACRONIX_MX25R8035F:1,
        BTL_STORAGE_SPIFLASH_MACRONIX_MX25R3235F:1,
        SLOT_OVERLAP_ENABLE:0,
        SLOT0_ENABLE:1,
        SLOT0_START:8192,
        SLOT0_SIZE:393216,
        SLOT1_ENABLE:1,
        SLOT1_START:401408,
        SLOT1_SIZE:393216,
      extra_c_defs: ""
      sdk_version: ${{ inputs.sdk_version }}
      sdkpatchpath: ''
      metadata_extra: "{}"
