# The entire pipeline was shamelessy borrowed from https://github.com/NabuCasa/silabs-firmware-builder
# Kudos to NabuCasa and Stefan

name: Silicon Labs builder

on:
  workflow_dispatch:
    inputs:
      build_btl:
        description: "Build Bootloader"
        required: false
        default: false
        type: boolean

  push:
    paths:
      - Dockerfile
      - .github/workflows/build.yaml
      - .github/workflows/app-btl-build.yaml
      - .github/workflows/silabs-project-builder.yaml
      - TBS2Torch/
      - patches/
    branches:
      - main
    tags:
      - '*'

env:
  sdk_version: ${{
      vars.sdk_version != ''
      && vars.sdk_version 
      || '4.3.0' 
    }}

jobs:
  build-container:
    name: Create build container image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    outputs:
      sdk_version: ${{ env.sdk_version }}
      image_name: ghcr.io/${{ steps.lower.outputs.repository_owner }}/silabs-project-builder:${{ env.sdk_version }}
    steps:
      - name: Repository owner lowercase
        id: lower
        run: |
          echo "repository_owner=$(echo $GITHUB_REPOSITORY_OWNER | tr [:upper:] [:lower:])" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v3.3.0

      - name: Log in to the GitHub container registry
        uses: docker/login-action@v2.1.0
        with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Build and Push
        uses: docker/build-push-action@v3.3.0
        with:
          context: .
          file: Dockerfile
          tags: ghcr.io/${{ steps.lower.outputs.repository_owner }}/silabs-project-builder:${{ env.sdk_version }}
          cache-from: ghcr.io/${{ steps.lower.outputs.repository_owner }}/silabs-project-builder:cache-${{ env.sdk_version }}
          cache-to: ghcr.io/${{ steps.lower.outputs.repository_owner }}/silabs-project-builder:cache-${{ env.sdk_version }}
          push: true
          build-args:
            "GECKO_SDK_VERSION=v${{ env.sdk_version }}"


  app-btl-build:
    name: Zigbee Torch App
    needs: build-container
    strategy:
      matrix:
        include:
          - device: EFR32MG12P332F1024GL125
            board: brd4166a
    uses: ./.github/workflows/app-btl-build.yaml
    with:
      sdk_version: ${{ needs.build-container.outputs.sdk_version }}
      device: ${{ matrix.device }}
      board: ${{ matrix.board }}
      build_btl: ${{ inputs.build_btl }}
      image_name: ${{ needs.build-container.outputs.image_name }}
